[tool.poetry]
name = "fishsense-lite-python-pipeline"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.24.1"
opencv-python = "4.7.0.72"
opencv-contrib-python = "4.7.0.72"
matplotlib = "^3.6.3"
tqdm = "^4.64.1"
scikit-image = "^0.19.3"
rawpy = "^0.18.1"
numba = "^0.57.1"

[tool.poetry.dev-dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
